version: "3.8"

services:
  app:
    container_name: notification
    build:
      context: .
      dockerfile: docker/python/Dockerfile
    env_file:
      - .env
    volumes:
      - ./:/app
    depends_on:
      - db
    ports:
      - 8000:8000
    command: /bin/sh -c "uv run uvicorn src.main:app --host=0.0.0.0 --port=8000 --reload"

  db:
    image: mongo:6
    container_name: notification-db
    volumes:
      - ./docker/mongodb/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
    ports:
      - 27017:27017
